from rest_framework import serializers
from .models import Movie, Seat, Booking

# Generated by Claude (Anthropic)
class MovieSerializer(serializers.ModelSerializer):
    class Meta:
        model = Movie 
        fields = '__all__'

# Generated by Claude (Anthropic)
class SeatSerializer(serializers.ModelSerializer):
    class Meta:
        model = Seat 
        fields = '__all__'

# Generated by Claude (Anthropic)
class BookingSerializer(serializers.ModelSerializer):
    class Meta:
        model = Booking 
        fields = '__all__'