# Generated by Django 5.1.6 on 2025-02-25 01:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_alter_booking_user'),
    ]

    operations = [
    ]
