# Generated by Django 5.1.6 on 2025-02-26 15:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0003_auto_20250224_1823'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='descrition',
            new_name='description',
        ),
    ]
