# Generated by Django 5.1.6 on 2025-02-27 04:36

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0004_rename_descrition_movie_description'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='booking',
            unique_together={('seat', 'booking_date', 'user')},
        ),
    ]
