# Generated by Django 4.2.11 on 2025-03-03 00:12

import datetime
import django.core.validators
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0013_alter_movie_poster'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='booking_date',
            field=models.DateField(default=django.utils.timezone.now, validators=[django.core.validators.MinValueValidator(datetime.date(2025, 3, 3)), django.core.validators.MaxValueValidator(datetime.timedelta(days=90))]),
        ),
    ]
