# Generated by Django 4.2.11 on 2025-03-03 21:14

import datetime
import django.core.validators
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0014_alter_booking_booking_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='booking_date',
            field=models.DateField(default=django.utils.timezone.now, validators=[django.core.validators.MinValueValidator(django.utils.timezone.now), django.core.validators.MaxValueValidator(datetime.timedelta(days=90))]),
        ),
    ]
