# Generated by Django 4.2.11 on 2025-03-04 00:41

import bookings.models
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0015_alter_booking_booking_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='booking_date',
            field=models.DateField(default=django.utils.timezone.now, validators=[bookings.models.validate_booking_date]),
        ),
    ]
