# Generated by Django 4.2.11 on 2025-03-04 00:54

import bookings.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0016_alter_booking_booking_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seat',
            name='seat_number',
            field=models.SmallIntegerField(unique=True, validators=[bookings.models.validate_seating_number]),
        ),
    ]
